import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";

import { Footer } from "@/components/footer";
import { QueryProvider } from "@/lib/query-client";

import "./globals.css";

const space_grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solvro Web Template",
  description: "Generated by create next app with solvro config",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <QueryProvider>
        <body
          className={`${space_grotesk.variable} flex min-h-screen flex-col bg-gradient-to-br from-slate-950 to-blue-900 font-sans antialiased`}
        >
          <div className="flex-grow">{children}</div>
          <Footer />
        </body>
      </QueryProvider>
    </html>
  );
}
